Milestone 1 branch
MohameDawood/tic_tac_toe pull request #2
Opened 2020-10-26 09:48 UTC by daviidy

We created 2 main directories:

- lib - for the game logic

- bin - with the main.rb file

We made our main.rb file displaying “Hello world!” when we use bin/main.rb as a bash command.

2020-10-26 11:02 UTC, moinkhanif requested changes
## Changes Required ❗

Hey team, nice work implementing Milestone 1 so far. However, please **fix** the requested changes in the **comments below** to move forward with this project. 👍

If you have any questions, you can reach out to me on slack at @moinkhanif.
**Happy Coding!**

2020-10-26 11:02 UTC, moinkhanif commented on bin/main.rb
> +#!/usr/bin/env ruby
- [x] **[REQUIRED]** As pointed out by the linter, and also the project specifications, the `main.rb` file doesn't have executable permissions. Test if executable file works (bin/main.rb displays message as well as ruby bin/main.rb) and fix this, please.
Reference project specification: ![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png)

-  [x] **[REQUIRED]** After implementing the above change, please fix any linter errors before project submission.

2020-10-26 16:33 UTC, kubilaycaglayan requested changes
#### Hello Team 👋
#### Status: Changes Required ♻️

Great job so far! 👏👋
Let's cover a few details together to make your project better 😊⏬

### Read the Documents Please 😇

💡 This will be a kind of repetition of the last review. 😇
After you read the documentation, please let me know if you need anything more, through Slack.

- https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/

- [ ] [REQUIRED] `main.rb` is an [executable file](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/):
  - `#!/usr/bin/env ruby` is the top line (you shouldn't delete it)
  - puts "Hello world" in the following line
    ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [ ] [REQUIRED] Executable file should work with these commands:
 - `bin/main.rb`
 - `ruby bin/main.rb`)
 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

 📸 Screenshot from the project

![image](https://user-images.githubusercontent.com/60448833/97199833-873d4a80-17c1-11eb-8592-870142b1bfd9.png)

 📸 Screenshot from the file properties

![image](https://user-images.githubusercontent.com/60448833/97199935-a6d47300-17c1-11eb-93b3-dfcbe627b093.png)

## That's it, you can request another code review request after making the changes ♻️😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-10-27 12:48 UTC, mimipeshy commented
### STATUS : APPROVED !! :partying_face:  :dancers: 
Congratulations in making the required changes. This milestone is approved !!  :clap:  :clap: Good luck in the next project !!

Happy Coding :computer: 

Peris Ndanu

2020-10-27 13:04 UTC, merged